# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: spring-petclinic-langchain4j

workflows:
  up:
    - azd: provision
    - azd: package --all
    - azd: deploy --all

infra:
  provider: bicep
  path: infra/bicep

services:
  petclinic-ai:
    resourceName: petclinic-langchain4j
    project: ./
    host: containerapp
    language: java
    docker:
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      image: spring-petclinic-langchain4j/petclinic-langchain4j
      tag: ${AZD_PROVISION_TIMESTAMP}
      remoteBuild: true

hooks:
  prepackage:
    posix:
      shell: sh
      run: 'chmod +x ./mvnw; ./mvnw clean package -DskipTests'
